apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopsdep
  name: devopsdep
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopsdep
  template:
    metadata:
      labels:
        app: devopsdep
    spec:
      containers:
        - image: briankimathi/pythonapp:b858809f409e1accdc2d2e6125408eb5cd6f9195
          name: pythonapp
