# Devops Github Actions Workflow for CI/CD
name: Devops CICD Pipeline

on: 
  push:
    branches: 
      - main 
    paths-ignore:
      - ./manifests

jobs:
  devops-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        file: ./Dockerfile
        tags: briankimathi/pythonapp:${{ github.sha }}
        push: true
    - name: Updating image tag inside manifest files
      run: |
        pip install yq
        yq -Yi '.spec.template.spec.containers[0].image = "briankimathi/pythonapp:${{ github.sha }}"' ./manifests/02_devopsdep.yaml
    - name: Commit and Push the code
      run: |
        git config user.name "Brian Kimathi"
        git config user.email "kimathibrian71@gmail.com"
        git commit -m "Updating image tag inside manifest using actions"
        git push origin main
